### ISSUE TITLE
Add wavy lines to UI

### ISSUE THREAD

**Issue by Lotes** [Lotes/bindings-lang#5]
```css
div.b {
  text-decoration-line: underline;
  text-decoration-style: wavy;
  text-decoration-color: red;
}
```
